linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Vonage/vonage-cloud-runtime-cli
  gocyclo:
    min-complexity: 10

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - .git
    - node_modules

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - funlen
    - wsl
    - lll
    - exhaustivestruct
    - wrapcheck
    - exhaustruct
    - forbidigo
    - gocyclo
    - godot
    - gofumpt
    - depguard
    - goerr113
    - ifshort
    - interfacebloat
    - ireturn
    - paralleltest
    - testifylint
    - testpackage
    - varnamelen
    - tagliatelle
    - nlreturn
    - noctx
    - gomnd
    - forcetypeassert
    - cyclop
    - whitespace
    - revive
    - goimports
    - gci
    - scopelint
    - godox
    - gosec
    - nestif
    - tagalign
    - mirror
    - ineffassign
    - thelper
    - usestdlibvars
    - perfsprint
    - nosnakecase
    - contextcheck
    - maligned
    - goconst
    - unconvert
    - durationcheck
    - usestdlibvars
    - thelper
    - predeclared
    - staticcheck
    - perfsprint
    - maintidx
    - prealloc
    - unparam

issues:
  exclude-rules:
    - text: "don't use an underscore in package name"
      linters:
        - golint
    - text: "package comment should be of the form"
      linters:
        - golint
    - path: (.+)_test.go
      linters:
        - funlen
        - goconst
        - dupl
        - errcheck
        - exhaustivestruct
        - errorlint
        - gocognit
        - structcheck
    - path: tests/integration
      linters:
        - funlen
        - goconst
        - dupl
        - errcheck
        - exhaustivestruct
        - errorlint
        - structcheck