linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/Vonage/vonage-cloud-runtime-cli
  gocyclo:
    min-complexity: 10

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - .git
    - node_modules

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - funlen
    - wsl
    - lll

issues:
  exclude-rules:
    - text: "don't use an underscore in package name"
      linters:
        - golint
    - text: "package comment should be of the form"
      linters:
        - golint