version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - goconst
    - gocyclo
    - cyclop
    - errname
    - errorlint
    - gocritic
    - goprintffuncname
    - nilerr
    - rowserrcheck
    - sqlclosecheck
  settings:
    gocyclo:
      min-complexity: 25
    cyclop:
      max-complexity: 25

  exclusions:
    rules:
      - text: "Error return value of `.*Close` is not checked"
        linters:
          - errcheck
      - text: "Error return value of `fmt.Fprint` is not checked"
        linters:
          - errcheck
      - text: "Error return value of `fmt.Fprintf` is not checked"
        linters:
          - errcheck
      - text: "Error return value of `fmt.Fprintln` is not checked"
        linters:
          - errcheck
      - text: "don't use an underscore in package name"
        linters:
          - golint
      - text: "package comment should be of the form"
        linters:
          - golint
      - path: _test\.go
        linters:
          - funlen
          - goconst
          - dupl
          - gocognit
          - testifylint
          - cyclop
          - gocyclo
          - errcheck
      - path: tests/integration
        linters:
          - funlen
          - goconst
          - dupl
          - cyclop
          - gocyclo     


