FROM golang:1.24.0

WORKDIR /app

COPY . .

RUN go mod download

RUN go build -o mockserver /app/tests/integration/mocks/main.go

RUN chmod +x /app/tests/integration/scripts/run_mockserver.sh

CMD ["/app/tests/integration/scripts/run_mockserver.sh"]