name: Semantic-Version-Bump
on:
  push:
    branches:
      - main
jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: vcp-runner
    steps:
      - uses: actions/checkout@v3
      - uses: jefflinse/pr-semver-bump@v1.3.3
        name: Bump and Tag Version
        with:
          mode: bump
          repo-token:  ${{ secrets.GITHUB_TOKEN }} 
          major-label: major release
          minor-label: minor release
          patch-label: patch release
          require-release-notes: true
          release-notes-prefix: ''
          release-notes-suffix: ''
          with-v: false
